spring.application.name=Tunja_Evenfy
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/evenfy_db
spring.datasource.username=user_api
spring.datasource.password=1234
spring.jackson.serialization.fail-on-empty-beans=false
logging.level.org.hibernate=ERROR
spring.jpa.properties.hibernate.jdbc.lab.non_contextual_creation=true
spring.docker.compose.enabled=false

# ========== EMAIL CONFIGURATION (Gmail) ==========
# Nota: Usar contraseña de aplicación, no la contraseña de Gmail normal
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cesarmlh27@gmail.com
spring.mail.password=zvabzbzvdteewyff
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ========== JWT CONFIGURATION ==========
jwt.secret=tunja-evenfy-secret-key-2024-super-secure-key-for-jwt-tokens-change-in-production
jwt.expiration=86400000

# ========== RESEND EMAIL CONFIGURATION ==========
resend.api.key=re_V71WLtQx_9Zs5sjjrZYw4aJ4knMvR3fod
